### ISSUE TITLE
Run without sketch

### ISSUE THREAD

**Issue by rohitpaul23** [aimagelab/multimodal-garment-designer#10]
Earlier in the issue(https://github.com/aimagelab/multimodal-garment-designer/issues/8#issuecomment-1638829483) you mentioned using sketch_cond_rate=0.0 for that. 

I tried the following script !python eval.py --dataset_path assets/data/testVitonhd --batch_size 1 --mixed_precision fp16 --output_dir testOutput --save_name test_out_vitonhd_0_0 --num_workers_test 1 --sketch_cond_rate 0.0 --dataset vitonhd --start_cond_rate 0.0,

where assets/data/testVitonhd has the same directory structure as assets/data/vitonhd from the repo, accept the test/im_sketch_unpaired and test/im_sketch which are removed

when runned its showing:
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File 
"/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/wo
rker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File 
"/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fe
tch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File 
"/opt/conda/envs/pytorch/lib/python3.10/site-packages/torch/utils/data/_utils/fe
tch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ec2-user/multimodal-garment-designer/datasets/vitonhd.py", line 
175, in __getitem__
    im_sketch = Image.open(
  File "/opt/conda/envs/pytorch/lib/python3.10/site-packages/PIL/Image.py", line
3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 
'assets/data/testVitonhd/test/im_sketch_unpaired/12419_00_01944_00.png'
 

please correct me whether I am doing right

Thank You

**Comment by rohitpaul23** [comment]
I got it as a random sketch can be kept in the desired location and since sketch_cond_rate is 0, it will not affect the results

**Comment by ABaldrati** [comment]
Hi @rohitpaul23,

Apologies for the delayed response, and thank you for your interest in our work!

You're right! Our model can run inference without considering the sketch. During inference, the pipeline automatically black-outs the sketch. However, in our current implementation, we still require a sketch image as input.

Glad to know that you figured it out on your own!

Best regards,
Alberto

**Comment by rohitpaul23** [comment]
Thank you for the reply,

@ABaldrati  I need another help. As I want to test your model on my custom dataset and so need to prepare the datasets. I might have miss something so how do i get the processed input, I guess label maps can be obtained using SCHP model trained on the ATR dataset. What about test stitch map and in keypoints each element is a list of 4 values, where it seems the first two are coordinates on the x and y axis respectively, what about the last two values.
Correct me if i am wrong

Thank you again
