### ISSUE TITLE
Preprocessed Input

### ISSUE THREAD

**Issue by rohitpaul23** [aimagelab/multimodal-garment-designer#11]
Thank you for the reply,

@ABaldrati  I need another help. As I want to test your model on my custom dataset and so need to prepare the datasets. I might have miss something so how do i get the processed input, I guess label maps can be obtained using SCHP model trained on the ATR dataset. What about test stitch map and in keypoints each element is a list of 4 values, where it seems the first two are coordinates on the x and y axis respectively, what about the last two values.
Correct me if i am wrong

Thank you again

_Originally posted by @rohitpaul23 in https://github.com/aimagelab/multimodal-garment-designer/issues/10#issuecomment-1656579657_

**Comment by rohitpaul23** [comment]
I somehow understand the keypoints 4 values(x, y, confidence, indices), but was not able to reflect the values of assets/data/dresscode/dresses/keypoints/052012_2.json from the assets/data/dresscode/dresses/images/052012_0.jpg images.

So has some doubt regarding that:
1. whether resizing is done(it seem though) before the processing
2. how come we are getting the keypoints for index 15, 16 and 17 as it seems the image doesn't have the upper face

**also how do we get the stitch map

please help !!

**Comment by rohitpaul23** [comment]
have gone through the https://github.com/Hzzone/pytorch-openpose and found the weight to get the correct keypoints, as it seems the input images is resized to (512, 384) so to get the desired keypoints as per above.
It seems the stitch map is obtained using 'lip'

Please confirm !!

**Comment by lynguyenminh** [comment]
Hi, 
Have you resolved this issue yet? If you can, please share it with me. Thank you very much!

**Comment by giuseppecartella** [comment]
Hi @rohitpaul23,

Thanks for your interest in our work and sorry for the late reply. 
You are right, the label maps are obtained through the SCHP model trained on ATR. 

Dress Code is annotated with keypoints obtained by the OpenPose model (version with 18 keypoints). Each keypoint is represented in the following form (x, y, prediction confidence of OpenPose, label of the keypoint (e.g. elbow, wrist etc...)).

This is the corresponding label for each keypoint (that you can also find in the readme file of the original Dress Code dataset):
keypoints_map={
    0.0: "nose",
    1.0: "neck",
    2.0: "right shoulder",
    3.0: "right elbow",
    4.0: "right wrist",
    5.0: "left shoulder",
    6.0: "left elbow",
    7.0: "left wrist",
    8.0: "right hip",
    9.0: "right knee",
    10.0: "right ankle",
    11.0: "left hip",
    12.0: "left knee",
    13.0: "left ankle",
    14.0: "right eye",
    15.0: "left eye",
    16.0: "right ear",
    17.0: "left ear"
}

Instead, the segmentations of the test_stitch_map are obtained with SCHP trained on the LIP dataset. This version of the model allows the separation of the face from the neck during the image composition step.

Giuseppe
