### ISSUE TITLE
Generating complete model images using pose map, textual description and shape of garment only

### ISSUE THREAD

**Issue by madmaverickminion** [aimagelab/multimodal-garment-designer#13]
Hi 
First of all thanks for publishing this paper. It is quite interesting. 
I was going through the paper. 
 Quoting one of the paragraphs:
> Specifically, given the model image I ∈
> R H×W ×3 , its pose map P ∈ R H×W ×18 where the chan-
> nels represent the human keypoints, a textual description Y
> of a garment, and a sketch of the same S ∈ R H×W ×1 , we
> want to generate a new image I ˜ ∈ R H×W ×3 that retains the
> information of the input model while substituting the target
> garment according to the multimodal inputs.

I was wondering could we create full model images artificially, using just human keypoints, sketches of garments and textual descriptions, without needing an actual image of the model? 

Thank you!!

**Comment by ABaldrati** [comment]
Hi @madmaverickminion 
Thanks for your interest in our work!!



> I was wondering could we create full model images artificially, using just human keypoints, sketches of garments and textual descriptions, without needing an actual image of the model?

I think it should be possible.
In this case, you wouldn't need to adapt an inpainting model but you should adapt a standard text-to-image model (if you want to follow the same approach as us).

Alberto
