### ISSUE TITLE
environment setup

### ISSUE THREAD

**Issue by amansaini25** [aimagelab/multimodal-garment-designer#16]
Thanks for your great contribution!
Can we please get the requirements.txt file for the libraries you have tested this? because It's taking lot of time for me to debug import issues

**Comment by ABaldrati** [comment]
Hi @CRAZYMONTY 
Thanks for your interest in our work!!

In the README we now provide info about the requirements needed for running the project

Hope this helps and solves your issue!

Best
Alberto
