### ISSUE TITLE
how to make keypoints

### ISSUE THREAD

**Issue by StartHua** [aimagelab/multimodal-garment-designer#18]
how to make keypoints

**Comment by ABaldrati** [comment]
Hi @StartHua 
Thanks for your interest in our work!!

We used the keypoints provided by the DressCode and VitonHD datasets. Refer to their paper to know how they have extracted these keypoints.

If I am not mistaken I think they used [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) but I could be wrong

Best,
Alberto

**Comment by giuseppecartella** [comment]
Hi @StartHua, 
As Alberto said keypoints are extracted from OpenPose.
The OpenPose version trained on human data is applied. It gives as output 18 keypoints.

Each keypoint is in the following form: [x, y, confidence of the model, label of the keypoint].
In the readme of the Dress Code dataset (when you download it) you find the interpration of each keypoint.
I report it here:

keypoints_map={
0.0: "nose",
1.0: "neck",
2.0: "right shoulder",
3.0: "right elbow",
4.0: "right wrist",
5.0: "left shoulder",
6.0: "left elbow",
7.0: "left wrist",
8.0: "right hip",
9.0: "right knee",
10.0: "right ankle",
11.0: "left hip",
12.0: "left knee",
13.0: "left ankle",
14.0: "right eye",
15.0: "left eye",
16.0: "right ear",
17.0: "left ear"
}

Giuseppe
