### ISSUE TITLE
I can't find test_stitch_map in Dress Code Multimodal

### ISSUE THREAD

**Issue by zengjianhao** [aimagelab/multimodal-garment-designer#19]
After I decompressed Dress Code Multimodal, I could only get the following files, without the test_stitch_map in the README.

<img width="223" alt="image" src="https://github.com/aimagelab/multimodal-garment-designer/assets/98309632/1e1092d4-61fc-4db3-89dd-ef707cf044fb">
<img width="595" alt="image" src="https://github.com/aimagelab/multimodal-garment-designer/assets/98309632/68c82d7d-c0fd-415d-9f7d-3671dd33b0de">

**Comment by ABaldrati** [comment]
Hi @zengjianhao 

You are right!
We made a mistake during the release of the extended datasets.
Now the *Dress Code Multimodal* [[link](https://drive.google.com/file/d/1dwnAi1CNmmF_YdbIDfm8078dGh4ci47L/view?usp=sharing)] dataset should contain the `test_stich_map` folder.

Best,
Alberto
