### ISSUE TITLE
What is the VRAM requirement of multimodal-garment-designer?

### ISSUE THREAD

**Issue by Njasa2k** [aimagelab/multimodal-garment-designer#2]

**Comment by ABaldrati** [comment]
Hi @ninjasaid2k 
Thanks for your interest in our work!

The minimum amount of VRAM required for training is about 18GB (when using batch size equal to 1 and leveraging the [xformers](https://github.com/facebookresearch/xformers) library).

At inference time the amount of VRAM required is roughly the same as the out-of-the-shelf stable diffusion, i.e. you can run the inference with less than 6GB of VRAM.

If you have any further questions do not hesitate to ask.

**Comment by kadirnar** [comment]
When will you publish the codes?

**Comment by omedivad** [comment]
Hi @kadirnar,

We plan to release the inference code and the network weights in a few weeks.
We will release the train code and the dataset upon paper acceptance.

Thanks for your interest in our research.
