### ISSUE TITLE
How to download the UNet model?

### ISSUE THREAD

**Issue by wly-ai-bj** [aimagelab/multimodal-garment-designer#27]
```python
import torch
unet = torch.hub.load(
    dataset='dresscode', 
    repo_or_dir='aimagelab/multimodal-garment-designer', 
    source='github', 
    model='mgd', 
    pretrained=True
    )
```
按照这个脚本，下载失败。
按照这个网址https://github.com/aimagelab/multimodal-garment-designer/releases/download/weights/{dataset}.pth去下载，显示页面找不到。

**Comment by AAKillua** [comment]
It can be downloaded at this URL:[https://github.com/aimagelab/multimodal-garment-designer/releases/download/weights/dresscode.pth
