### ISSUE TITLE
inference result quality

### ISSUE THREAD

**Issue by zhangai6666** [aimagelab/multimodal-garment-designer#6]
After running the inference command on DressCode dataset . The result using test_pairs_unpaired.txt has some unexpected distortion on the body(picture attached), especially the missing arms. Maybe I'm missing something.  I would greatly appreciate it if someone could help take a look. Let me know if you would like me to create a debug repo. Thank you so much!

Output Image:
![052012_0](https://github.com/aimagelab/multimodal-garment-designer/assets/10181307/4f45fb22-c861-4098-b472-18c26615514a)

052012_0.jpg    052033_1.jpg

**Comment by omedivad** [comment]
Hi @Dennisboyangzhang!

Thanks for your interest in our work. 
Could you please copy and paste the command you used to produce this image?

As for us, this is our results with the command:

```
python eval.py --dataset_path <path_to_dataset> --pretrained_model_name_or_path runwayml/stable-diffusion-inpainting --seed 1234 --batch_size 2  --mixed_precision fp16 --output_dir output_dresscode --num_workers_test 6 --mask_type bounding_box --test_order unpaired save_name test --sketch_cond_rate 0.2 --dataset dresscode --start_cond_rate 0.0
```

![052012_0](https://github.com/aimagelab/multimodal-garment-designer/assets/34794182/5e082932-5be4-4b9f-99f6-7cadfdb5862e)

**Comment by zhangai6666** [comment]
Hi @omedivad 

Thank you so much for your comment!  After switching to the exact same command in your comment, The following error is showing up.  After searching it online, I suspect my pretrained model preparation has issue.  I used "git clone https://huggingface.co/runwayml/stable-diffusion-inpainting" to create the pretrained directory. Could you please let me know if it is expected?  

I also attached the screenshot of my WORKDIR in the end. Let me know if anything is missing. 

One interesting thing I couldn't figure out is, If I run the latest command with "--category dresses", the run is able to finish without error. However, the result was bad, as listed in the first comment.

Error Stack
`Traceback (most recent call last):
  File "eval.py", line 157, in <module>
    main()
  File "eval.py", line 152, in main
    seed = args.seed,
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\denni\Source\Repos\multimodal-garment-designer\utils\image_from_pipe.py", line 58, in generate_images_from_inpaint_sketch_posemap_pipe
    for batch in tqdm(test_dataloader):
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\accelerate\data_loader.py", line 387, in __iter__
    next_batch = next(dataloader_iter)
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\denni\Source\Repos\multimodal-garment-designer\datasets\dresscode.py", line 365, in __getitem__
    bboxes = masks_to_boxes(inpaint_mask.unsqueeze(0))
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torchvision\ops\boxes.py", line 412, in masks_to_boxes
    bounding_boxes[index, 0] = torch.min(x)
RuntimeError: min(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.`

![image](https://github.com/aimagelab/multimodal-garment-designer/assets/10181307/8fe95e2f-ed40-48c1-9387-e22614de2baa)

**Comment by omedivad** [comment]
Hi @Dennisboyangzhang,

You don't need to prepare the pre-trained directory nor clone the stable diffusion inpainting repo. The code automatically takes the weights from the "Weights release" in this repo.

You just need to clone the repo and run the inference command to try it on sample data. Otherwise, as pointed out in the README, you need to download the datasets and the annotations, hence merging the corresponding dataset folder with the corresponding annotations folder.

Regarding your _Error Stack_, it seems you have some issues with the dresscode.py file. 

What troubles me is that you have a problem in

File "C:\Users\denni\Source\Repos\multimodal-garment-designer\datasets\dresscode.py",  line 365, in __getitem__ bboxes = masks_to_boxes(inpaint_mask.unsqueeze(0))

while this line of code (bboxes = masks_to_boxes(inpaint_mask.unsqueeze(0))) should be line 385 of the same file.
It seems the dresscode.py file has been somehow modified, and you are missing 20 lines of code.

Please try to clone our repo again from scratch and tell me if you can run the code using the command I wrote in the previous comment.

Let me know the outcome.

Best,

Davide

**Comment by zhangai6666** [comment]
Hi @omedivad, 

Thank you so much for the comment! I did change dresscode.py a few days ago in order to get the run going. Now I cloned the  repo from scratch and run the command 

`python eval.py --dataset_path <path_to_dataset> --pretrained_model_name_or_path runwayml/stable-diffusion-inpainting --seed 1234 --batch_size 2  --mixed_precision fp16 --output_dir output_dresscode --num_workers_test 6 --mask_type bounding_box --test_order unpaired save_name test --sketch_cond_rate 0.2 --dataset dresscode --start_cond_rate 0.0`

The following error shows up. It's better to ask for your advice than me hacking around.  Could you please help let me know what should I do? Thanks a lot!

`(mgd) PS C:\Users\denni\Source\multimodal-garment-designer> python eval.py --dataset_path D:\DATA\DressCode\DressCode --pretrained_model_name_or_path runwayml/stable-diffusion-inpainting --seed 1234 --batch_size 2  --mixed_precision fp16 --output_dir output_dresscode --num_workers_test 6 --mask_type bounding_box --test_order unpaired --save_name test --sketch_cond_rate 0.2 --dataset dresscode --start_cond_rate 0.0
C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
Using cache found in C:\Users\denni/.cache\torch\hub\aimagelab_multimodal-garment-designer_main
  0%|                                                                                                                                                                      | 0/2 [00:00<?, ?it/s]C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
C:\Users\denni\Source\multimodal-garment-designer\pipes\sketch_posemap_inpaint_pipe.py:13: FutureWarning: Importing `DiffusionPipeline` or `ImagePipelineOutput` from diffusers.pipeline_utils is deprecated. Please import from diffusers.pipelines.pipeline_utils instead.
  from diffusers.pipeline_utils import DiffusionPipeline
  0%|                                                                                                                                                                      | 0/2 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 157, in <module>
    main()
  File "eval.py", line 152, in main
    seed = args.seed,
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\denni\Source\multimodal-garment-designer\utils\image_from_pipe.py", line 58, in generate_images_from_inpaint_sketch_posemap_pipe
    for batch in tqdm(test_dataloader):
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\accelerate\data_loader.py", line 377, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
NotImplementedError: Caught NotImplementedError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\denni\miniconda3\envs\mgd\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\denni\Source\multimodal-garment-designer\datasets\dresscode.py", line 247, in __getitem__
    raise NotImplementedError
NotImplementedError`

**Comment by omedivad** [comment]
It seems your Dress Code dataset folder is incorrect, or the tree inside your folder has been modified.

You passed as a parameter of the argument _--dataset_path_ the path _D:\DATA\DressCode\DressCode_.
I assume you are trying the code on the test set of the whole Dress Code dataset.

Make sure inside the _D:\DATA\DressCode\DressCode_ path you have the following tree:

```
DressCode
|-- upper_body
|-- lower_body
|-- dresses
...
```

It seems the code cannot find these category folders.

Can you post a snapshot of the Dress Code dataset folder tree?

**Comment by zhangai6666** [comment]
Thanks a lot! 

![image](https://github.com/aimagelab/multimodal-garment-designer/assets/10181307/e51e4840-83b2-483b-81da-f79ce8b3de4e)


Let me know if you need more information. Thank you so much!

**Comment by zhangai6666** [comment]
Snapshot on secondary directories:

![image](https://github.com/aimagelab/multimodal-garment-designer/assets/10181307/397329f2-fe63-49e0-b952-08710dc732ea)

![image](https://github.com/aimagelab/multimodal-garment-designer/assets/10181307/31c4dca7-dcf8-4b19-93ef-1bc8cd212e01)

![image](https://github.com/aimagelab/multimodal-garment-designer/assets/10181307/d0caf1e4-d26e-4a59-be38-71caf27c204b)

**Comment by omedivad** [comment]
Hi @Dennisboyangzhang,

the code was not compliant with Windows. We should have fixed that now. 
Please pull the code from git and try again.

Let me know if it works now.
Thanks.

Davide

**Comment by zhangai6666** [comment]
Hi @omedivad,

Thank you so much for the updates!  I have generated the same result for the default testcase. Could you please release the pretrained warping module(Paper Section A.4), so I can test on other testcases? Thanks a lot.

**Comment by omedivad** [comment]
Hi @Dennisboyangzhang,

Thanks for reporting the issue. Now our code can run on windows too.
We are not planning to release the pre-trained warping module since it is specific to the domain it was trained on, and we have already released the warped sketches.
However, in the paper, you can find all the information to train a warping module yourself.

Best regards,

Davide
