### ISSUE TITLE
About the perceptual loss during the training phase.

### ISSUE THREAD

**Issue by WindVChen** [aimagelab/multimodal-garment-designer#7]
Hi, 

It is an excellent work. I noticed that you mentioned in the paper that training leveraged the perceptual loss besides L1 loss. Could you give more details about that? It is easy to understand the L1 loss (which is similar to the L2 loss in the original LDM); however, how can we leverage the perceptual loss to supervise the training phase? Do we apply the perceptual loss directly on the noisy latent $x_t$?

Looking forward to your reply, thanks.

**Comment by omedivad** [comment]
Hello @WindVChen,

We used the perceptual loss only during the train of the Warping Module, which is used to extract the sketches in the unpaired settings.

We did use only the l1 loss during the training of the denoising network.

Best.

Davide

**Comment by WindVChen** [comment]
Oh, thanks. I got it wrong earlier.
