### ISSUE TITLE
Is it possible run inference without sketches?

### ISSUE THREAD

**Issue by dmangla3** [aimagelab/multimodal-garment-designer#8]
Hi, as you have mentioned in [this issue](https://github.com/aimagelab/multimodal-garment-designer/issues/1) that `, and our model can work when some of the input conditions are missing`, I just wanted to know if we can run inference without sketches? If yes, can you please share the command or procedure to do that?

**Comment by omedivad** [comment]
Hi @i-amgeek!

Thanks for your interest in our work.
To run the inference without a sketch, you need to set the parameter `sketch_cond_rate=0.0`.

Best,

Davide
